// InstaBOT — shared configuration
// Dynamically loads NGROK_URL from .env.local if available

// Step 1: BASE_URL — localhost:8000 in dev, ngrok when .env.local exists
let BASE_URL = window.BASE_URL || window.location.origin;
window.BASE_URL = BASE_URL;

// Try to load NGROK_URL from .env.local (generated by npm run tunnel)
fetch('.env.local')
  .then((r) => {
    if (!r.ok) throw new Error('No .env.local');
    return r.text();
  })
  .then((txt) => {
    const match = txt.match(/NGROK_URL=([^\n]+)/);
    if (match) {
      BASE_URL = match[1].trim();
      window.BASE_URL = BASE_URL;
      console.log('🔗 Using ngrok tunnel as BASE_URL:', BASE_URL);
    }
  })
  .catch(() => {
    // No .env.local fallback - use localhost
    BASE_URL = window.location.origin;
    window.BASE_URL = BASE_URL;
    console.log('⚠️  No ngrok tunnel detected. Using:', BASE_URL);
  });

// Step 2: Supabase Configuration
const APP_CONFIG = {
  name: 'InstaAutomate',
  supabaseUrl: 'https://ssuqvxfgraphgcnybxcj.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdXF2eGZncmFwaGdjbnlieGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxOTM1NjEsImV4cCI6MjA5NDc2OTU2MX0.90N1IDt5QUffn2BVixbpCot-fsuvEHsPpusa-ecACOo',
  defaultAppId: '1503208814932037',
  
  // OAuth redirect (must exactly match Meta "Valid OAuth Redirect URIs")
  get redirectUri() {
    return `https://instaaiautomation.vercel.app/oauth-callback.html`;
  },


  
  // Meta Facebook Login scopes (one-click connect — page + IG + webhooks)
  metaOAuthScopes: [
    'pages_show_list',
    'pages_read_engagement',
    'pages_manage_metadata',
    'instagram_basic',
    'instagram_manage_messages',
    'business_management'
  ].join(','),
  oauthScopes: [
    'instagram_business_basic',
    'instagram_business_manage_messages',
    'instagram_business_manage_comments'
  ].join(','),
  
  graphVersion: 'v23.0',
  instagramToken: '',
  instagramUserId: '',
  configRowId: '00000000-0000-0000-0000-000000000001',
  
  // Webhook URL points to Supabase edge function
  webhookUrl: 'https://ssuqvxfgraphgcnybxcj.supabase.co/functions/v1/instagram-webhook'
};

// Step 3: Expose to window for global access
window.BASE_URL = BASE_URL;
window.APP_CONFIG = APP_CONFIG;

// Debug logging
console.log('📋 App Configuration Loaded:');
console.log('   BASE_URL:', BASE_URL);
console.log('   Supabase:', APP_CONFIG.supabaseUrl);
console.log('   OAuth Redirect:', APP_CONFIG.redirectUri);
